import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { useTheme } from "../../../context/ThemeContext";

const BUNDLERS = ["vite", "webpack"];
const FRAMEWORKS = ["react", "vue", "vanilla"];
const CSS_PREPROCESSORS = ["none", "sass", "less"];

const DEFAULT_PORTS = {
  vite: 5173,
  webpack: 8080,
};

const createDefaultForm = () => ({
  bundler: "vite",
  framework: "react",
  useTypeScript: false,
  cssPreprocessor: "none",
  pathAlias: true,
  minify: true,
  devPort: DEFAULT_PORTS.vite,
  proxyEnabled: false,
  proxyPath: "/api",
  proxyTarget: "http://localhost:3000",
  exportFormat: "js",
});

const getFrameworkPluginImport = (framework, bundler) => {
  if (framework === "react") {
    return bundler === "vite"
      ? "import react from '@vitejs/plugin-react';"
      : "";
  }
  if (framework === "vue") {
    return bundler === "vite"
      ? "import vue from '@vitejs/plugin-vue';"
      : "";
  }
  return "";
};

const getFrameworkPluginUsage = (framework) => {
  if (framework === "react") return "react()";
  if (framework === "vue") return "vue()";
  return "";
};

const getWebpackFrameworkPreset = (framework, useTypeScript) => {
  if (framework === "react") {
    return useTypeScript
      ? ["@babel/preset-env", "@babel/preset-react", "@babel/preset-typescript"]
      : ["@babel/preset-env", "@babel/preset-react"];
  }
  if (framework === "vue") {
    return useTypeScript
      ? ["@babel/preset-env", "@babel/preset-typescript"]
      : ["@babel/preset-env"];
  }
  return useTypeScript
    ? ["@babel/preset-env", "@babel/preset-typescript"]
    : ["@babel/preset-env"];
};

const buildViteProxyBlock = (proxyEnabled, proxyPath, proxyTarget) => {
  if (!proxyEnabled) return "";
  const safePath = proxyPath.trim() || "/api";
  const safeTarget = proxyTarget.trim() || "http://localhost:3000";
  return `
    proxy: {
      '${safePath}': {
        target: '${safeTarget}',
        changeOrigin: true,
      },
    },`;
};

const buildViteAliasBlock = (pathAlias, useTypeScript) => {
  if (!pathAlias) {
    return { pathImport: "", aliasBlock: "" };
  }
  const pathImport = useTypeScript
    ? "import path from 'node:path';\n"
    : "import path from 'path';\n";
  return {
    pathImport,
    aliasBlock: `
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },`,
  };
};

const buildViteCssBlock = (cssPreprocessor) => {
  if (cssPreprocessor === "sass") {
    return `
  css: {
    preprocessorOptions: {
      scss: {
        // Global Sass variables/mixins can be injected here
        // additionalData: \`@use "./src/styles/variables" as *;\`,
      },
    },
  },`;
  }
  if (cssPreprocessor === "less") {
    return `
  css: {
    preprocessorOptions: {
      less: {
        javascriptEnabled: true,
      },
    },
  },`;
  }
  return "";
};

const buildViteTypeScriptBlock = (framework, useTypeScript) => {
  if (!useTypeScript || framework !== "react") return "";
  return `
  esbuild: {
    jsx: 'automatic',
  },`;
};

const generateViteConfig = (form) => {
  const {
    framework,
    useTypeScript,
    cssPreprocessor,
    pathAlias,
    minify,
    devPort,
    proxyEnabled,
    proxyPath,
    proxyTarget,
    exportFormat,
  } = form;

  const isTsOutput = exportFormat === "ts";
  const pluginImport = getFrameworkPluginImport(framework, "vite");
  const pluginUsage = getFrameworkPluginUsage(framework);
  const aliasConfig = buildViteAliasBlock(pathAlias, isTsOutput);
  const proxyBlock = buildViteProxyBlock(
    proxyEnabled,
    proxyPath,
    proxyTarget,
  );
  const cssBlock = buildViteCssBlock(cssPreprocessor);
  const tsBlock = buildViteTypeScriptBlock(framework, useTypeScript);
  const minifyValue = minify ? "'esbuild'" : "false";
  const pluginsBlock = pluginUsage
    ? `\n  plugins: [${pluginUsage}],`
    : "";

  const typeImport = isTsOutput
    ? "\nimport type { UserConfig } from 'vite';"
    : "";

  if (isTsOutput) {
    return `// Generated by DevTasks Bundler Configuration Generator

import { defineConfig } from 'vite';${typeImport}
${pluginImport ? `${pluginImport}\n` : ""}${aliasConfig.pathImport || ""}
export default defineConfig({${pluginsBlock}${aliasConfig.aliasBlock || ""}
  server: {
    port: ${devPort},${proxyBlock}
  },
  build: {
    minify: ${minifyValue},
  },${tsBlock}${cssBlock}
} satisfies UserConfig);
`;
  }

  return `// Generated by DevTasks Bundler Configuration Generator

import { defineConfig } from 'vite';
${pluginImport ? `${pluginImport}\n` : ""}${aliasConfig.pathImport || ""}
export default defineConfig({${pluginsBlock}${aliasConfig.aliasBlock || ""}
  server: {
    port: ${devPort},${proxyBlock}
  },
  build: {
    minify: ${minifyValue},
  },${tsBlock}${cssBlock}
});
`;
};

const buildWebpackCssRules = (cssPreprocessor) => {
  const styleLoader = `{ loader: 'style-loader' }`;
  const cssLoader = `{ loader: 'css-loader' }`;

  if (cssPreprocessor === "sass") {
    return `    {
      test: /\\.(css|scss|sass)$/i,
      use: [${styleLoader}, ${cssLoader}, { loader: 'sass-loader' }],
    },`;
  }
  if (cssPreprocessor === "less") {
    return `    {
      test: /\\.(css|less)$/i,
      use: [${styleLoader}, ${cssLoader}, { loader: 'less-loader' }],
    },`;
  }
  return `    {
      test: /\\.css$/i,
      use: [${styleLoader}, ${cssLoader}],
    },`;
};

const buildWebpackModuleRules = (form) => {
  const { framework, useTypeScript, cssPreprocessor } = form;
  const cssRule = buildWebpackCssRules(cssPreprocessor);
  const presets = getWebpackFrameworkPreset(framework, useTypeScript);
  const presetList = presets.map((p) => `'${p}'`).join(", ");

  const jsRule = useTypeScript
    ? `    {
      test: /\\.tsx?$/,
      use: {
        loader: 'ts-loader',
        options: {
          transpileOnly: true,
        },
      },
      exclude: /node_modules/,
    },`
    : `    {
      test: /\\.jsx?$/,
      exclude: /node_modules/,
      use: {
        loader: 'babel-loader',
        options: {
          presets: [${presetList}],
        },
      },
    },`;

  const vueRule =
    framework === "vue"
      ? `
    {
      test: /\\.vue$/,
      loader: 'vue-loader',
    },`
      : "";

  return `${jsRule}${vueRule}
${cssRule}`;
};

const buildWebpackResolveAlias = (pathAlias) => {
  if (!pathAlias) return "";
  return `
  resolve: {
    extensions: ['.tsx', '.ts', '.jsx', '.js'],
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },`;
};

const buildWebpackProxyBlock = (proxyEnabled, proxyPath, proxyTarget) => {
  if (!proxyEnabled) return "";
  const safePath = proxyPath.trim() || "/api";
  const safeTarget = proxyTarget.trim() || "http://localhost:3000";
  return `
      proxy: [
        {
          context: ['${safePath}'],
          target: '${safeTarget}',
          changeOrigin: true,
        },
      ],`;
};

const generateWebpackConfig = (form) => {
  const {
    framework,
    useTypeScript,
    pathAlias,
    minify,
    devPort,
    proxyEnabled,
    proxyPath,
    proxyTarget,
    exportFormat,
  } = form;

  const isTsOutput = exportFormat === "ts";
  const entryExt = useTypeScript ? "tsx" : "jsx";
  const entryFile =
    framework === "vanilla"
      ? useTypeScript
        ? "./src/index.ts"
        : "./src/index.js"
      : `./src/main.${entryExt}`;

  const moduleRules = buildWebpackModuleRules(form);
  const aliasBlock = buildWebpackResolveAlias(pathAlias);
  const proxyBlock = buildWebpackProxyBlock(
    proxyEnabled,
    proxyPath,
    proxyTarget,
  );
  const vuePlugin =
    framework === "vue"
      ? `\nconst { VueLoaderPlugin } = require('vue-loader');`
      : "";
  const vuePluginUsage =
    framework === "vue" ? "\n    new VueLoaderPlugin()," : "";
  const mode = minify ? "production" : "development";

  if (isTsOutput) {
    return `// Generated by DevTasks Bundler Configuration Generator

const path = require('node:path');
const HtmlWebpackPlugin = require('html-webpack-plugin');${vuePlugin}

/** @type {import('webpack').Configuration} */
module.exports = {
  mode: '${mode}',
  entry: '${entryFile}',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'assets/[name].[contenthash].js',
    clean: true,
  },${aliasBlock}
  module: {
    rules: [
${moduleRules}
    ],
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: './index.html',
    }),${vuePluginUsage}
  ],
  devServer: {
    port: ${devPort},
    hot: true,
    open: true,${proxyBlock}
  },
  devtool: '${minify ? "source-map" : "eval-source-map"}',
  optimization: {
    minimize: ${minify ? "true" : "false"},
  },
};
`;
  }

  return `// Generated by DevTasks Bundler Configuration Generator

const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');${vuePlugin}

module.exports = {
  mode: '${mode}',
  entry: '${entryFile}',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'assets/[name].[contenthash].js',
    clean: true,
  },${aliasBlock}
  module: {
    rules: [
${moduleRules}
    ],
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: './index.html',
    }),${vuePluginUsage}
  ],
  devServer: {
    port: ${devPort},
    hot: true,
    open: true,${proxyBlock}
  },
  devtool: '${minify ? "source-map" : "eval-source-map"}',
  optimization: {
    minimize: ${minify ? "true" : "false"},
  },
};
`;
};

const generateConfig = (form) => {
  if (form.bundler === "webpack") {
    return generateWebpackConfig(form);
  }
  return generateViteConfig(form);
};

const getOutputFilename = (form) => {
  if (form.bundler === "webpack") {
    return form.exportFormat === "ts" ? "webpack.config.ts" : "webpack.config.js";
  }
  return form.exportFormat === "ts" ? "vite.config.ts" : "vite.config.js";
};

const BundlerGenerator = () => {
  const { dark } = useTheme();
  const [form, setForm] = useState(createDefaultForm);

  const theme = {
    light: {
      wrapper: "bg-[#F8F9FA] text-zinc-900",
      card: "bg-white border-zinc-250/90 shadow-sm",
      headerBorder: "border-zinc-200",
      input:
        "bg-white border-zinc-250 text-zinc-900 focus:border-zinc-900 placeholder-zinc-400 focus:bg-white",
      buttonPrimary:
        "bg-zinc-900 text-white hover:bg-zinc-800 active:scale-[0.98]",
      buttonSecondary:
        "bg-white border-zinc-250 text-zinc-700 hover:bg-zinc-50 active:scale-[0.98]",
      label: "text-zinc-500",
      subCard: "bg-neutral-50 border-neutral-200",
      outputPre: "bg-[#F9FAFB] border-zinc-200 text-emerald-700",
      toggleActive: "bg-black text-white",
      toggleInactive: "bg-neutral-200 text-neutral-600",
    },
    dark: {
      wrapper: "bg-[#090A0F] text-zinc-100",
      card: "bg-zinc-900/50 border-zinc-800/80 shadow-[0_8px_30px_rgb(0,0,0,0.4)]",
      headerBorder: "border-zinc-800/85",
      input:
        "bg-zinc-950/60 border-zinc-800 text-white focus:border-zinc-500 placeholder-zinc-600 focus:bg-zinc-950",
      buttonPrimary:
        "bg-white text-zinc-950 hover:bg-zinc-100 active:scale-[0.98]",
      buttonSecondary:
        "bg-zinc-900 border-zinc-800/80 text-zinc-300 hover:bg-zinc-850 active:scale-[0.98]",
      label: "text-zinc-400",
      subCard: "bg-zinc-950/60 border-zinc-800",
      outputPre: "bg-zinc-950/80 border-zinc-800/80 text-emerald-400",
      toggleActive: "bg-white text-black",
      toggleInactive: "bg-zinc-800 text-zinc-400",
    },
  };
  const t = dark ? theme.dark : theme.light;

  const output = useMemo(() => generateConfig(form), [form]);
  const outputFilename = useMemo(() => getOutputFilename(form), [form]);

  const updateField = (field, value) => {
    setForm((prev) => ({ ...prev, [field]: value }));
  };

  const handleBundlerChange = (bundler) => {
    setForm((prev) => ({
      ...prev,
      bundler,
      devPort: DEFAULT_PORTS[bundler],
    }));
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(output);
      toast.success("Copied to clipboard", {
        style: { background: "#000000", color: "#ffffff" },
      });
    } catch {
      toast.error("Failed to copy", {
        style: { background: "#000000", color: "#ffffff" },
      });
    }
  };

  const handleDownload = () => {
    const blob = new Blob([output], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = outputFilename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success(`Downloaded ${outputFilename}`, {
      style: { background: "#000000", color: "#ffffff" },
    });
  };

  const inputClass = `w-full px-4 py-2.5 rounded-xl border text-sm outline-none transition-all duration-300 ${t.input}`;
  const labelClass = `text-xs font-black uppercase tracking-widest ${t.label}`;

  return (
    <div
      className={`min-h-[calc(100vh-76px)] px-4 py-8 flex items-start justify-center transition-colors duration-300 ${t.wrapper}`}
    >
      <title>Bundler Configuration Generator — DevTasks</title>
      <meta
        name="description"
        content="Generate Vite or Webpack configuration files from visual options. Fully offline."
      />

      <div
        className={`w-full max-w-6xl rounded-3xl border overflow-hidden transition-all duration-300 ${t.card}`}
      >
        <div
          className={`flex items-center gap-4 p-5 border-b ${t.headerBorder}`}
        >
          <Link
            to="/devutilities"
            className={`w-10 h-10 border rounded-xl flex items-center justify-center font-bold text-lg transition-all duration-200 ${t.buttonSecondary}`}
            title="Back to Utilities"
          >
            ←
          </Link>
          <div>
            <h1 className="text-xl font-black uppercase tracking-tight">
              Bundler Configuration Generator
            </h1>
            <p className={`text-xs font-semibold mt-0.5 ${t.label}`}>
              Generate copy-pasteable Vite or Webpack config files from visual
              choices. Fully offline.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 p-6">
          <div className="flex flex-col gap-5">
            <h2 className="text-xs font-black uppercase tracking-[0.2em]">
              Configuration
            </h2>

            <div className="flex flex-col gap-3">
              <span className={labelClass}>Build System</span>
              <div className="flex gap-2">
                {BUNDLERS.map((bundler) => (
                  <button
                    key={bundler}
                    type="button"
                    onClick={() => handleBundlerChange(bundler)}
                    className={`flex-1 px-4 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wide transition-all cursor-pointer ${
                      form.bundler === bundler ? t.toggleActive : t.toggleInactive
                    }`}
                  >
                    {bundler}
                  </button>
                ))}
              </div>
            </div>

            <div className="flex flex-col gap-3">
              <span className={labelClass}>Target Framework</span>
              <select
                value={form.framework}
                onChange={(e) => updateField("framework", e.target.value)}
                className={inputClass}
              >
                {FRAMEWORKS.map((framework) => (
                  <option key={framework} value={framework}>
                    {framework === "vanilla"
                      ? "Vanilla JS"
                      : framework.charAt(0).toUpperCase() + framework.slice(1)}
                  </option>
                ))}
              </select>
            </div>

            <div className="flex flex-col gap-3">
              <span className={labelClass}>Options</span>
              <div
                className={`rounded-2xl border p-4 flex flex-col gap-3 ${t.subCard}`}
              >
                <label className="flex items-center gap-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={form.useTypeScript}
                    onChange={(e) =>
                      updateField("useTypeScript", e.target.checked)
                    }
                    className="w-4 h-4 rounded accent-zinc-900"
                  />
                  <span className="text-sm font-bold uppercase tracking-wide">
                    TypeScript Support
                  </span>
                </label>

                <label className="flex items-center gap-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={form.pathAlias}
                    onChange={(e) => updateField("pathAlias", e.target.checked)}
                    className="w-4 h-4 rounded accent-zinc-900"
                  />
                  <span className="text-sm font-bold uppercase tracking-wide">
                    Path Alias (@/ → /src)
                  </span>
                </label>

                <label className="flex items-center gap-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={form.minify}
                    onChange={(e) => updateField("minify", e.target.checked)}
                    className="w-4 h-4 rounded accent-zinc-900"
                  />
                  <span className="text-sm font-bold uppercase tracking-wide">
                    Minification
                  </span>
                </label>
              </div>
            </div>

            <div className="flex flex-col gap-3">
              <span className={labelClass}>CSS Preprocessor</span>
              <select
                value={form.cssPreprocessor}
                onChange={(e) =>
                  updateField("cssPreprocessor", e.target.value)
                }
                className={inputClass}
              >
                {CSS_PREPROCESSORS.map((option) => (
                  <option key={option} value={option}>
                    {option === "none"
                      ? "None (plain CSS)"
                      : option.charAt(0).toUpperCase() + option.slice(1)}
                  </option>
                ))}
              </select>
            </div>

            <div className="flex flex-col gap-3">
              <span className={labelClass}>Dev Server</span>
              <div className="flex flex-col gap-2">
                <label className={labelClass}>Port</label>
                <input
                  type="number"
                  min={1}
                  max={65535}
                  value={form.devPort}
                  onChange={(e) =>
                    updateField("devPort", Number(e.target.value) || 1)
                  }
                  className={inputClass}
                />
              </div>

              <label className="flex items-center gap-3 cursor-pointer mt-1">
                <input
                  type="checkbox"
                  checked={form.proxyEnabled}
                  onChange={(e) =>
                    updateField("proxyEnabled", e.target.checked)
                  }
                  className="w-4 h-4 rounded accent-zinc-900"
                />
                <span className="text-sm font-bold uppercase tracking-wide">
                  Enable Proxy
                </span>
              </label>

              {form.proxyEnabled && (
                <div
                  className={`rounded-xl border p-3 flex flex-col gap-3 ${t.subCard}`}
                >
                  <div className="flex flex-col gap-2">
                    <label className={labelClass}>Proxy Path</label>
                    <input
                      type="text"
                      value={form.proxyPath}
                      onChange={(e) => updateField("proxyPath", e.target.value)}
                      placeholder="/api"
                      className={`${inputClass} font-mono`}
                    />
                  </div>
                  <div className="flex flex-col gap-2">
                    <label className={labelClass}>Proxy Target</label>
                    <input
                      type="text"
                      value={form.proxyTarget}
                      onChange={(e) =>
                        updateField("proxyTarget", e.target.value)
                      }
                      placeholder="http://localhost:3000"
                      className={`${inputClass} font-mono`}
                    />
                  </div>
                </div>
              )}
            </div>

            <div className="flex flex-col gap-3">
              <span className={labelClass}>Export Format</span>
              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={() => updateField("exportFormat", "js")}
                  className={`flex-1 px-4 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wide transition-all cursor-pointer ${
                    form.exportFormat === "js" ? t.toggleActive : t.toggleInactive
                  }`}
                >
                  JavaScript (.js)
                </button>
                <button
                  type="button"
                  onClick={() => updateField("exportFormat", "ts")}
                  className={`flex-1 px-4 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wide transition-all cursor-pointer ${
                    form.exportFormat === "ts" ? t.toggleActive : t.toggleInactive
                  }`}
                >
                  TypeScript (.ts)
                </button>
              </div>
              <p className={`text-[10px] font-medium ${t.label}`}>
                {form.bundler === "vite"
                  ? "Outputs vite.config.js or vite.config.ts with matching syntax."
                  : "Outputs webpack.config.js or webpack.config.ts with matching syntax."}
              </p>
            </div>
          </div>

          <div className="flex flex-col gap-4">
            <h2 className="text-xs font-black uppercase tracking-[0.2em]">
              Output
            </h2>

            <div
              className={`rounded-2xl border overflow-hidden flex flex-col ${t.outputPre}`}
            >
              <div
                className={`flex items-center justify-between px-4 py-3 border-b ${t.headerBorder}`}
              >
                <span className="text-xs font-black uppercase tracking-widest">
                  {outputFilename}
                </span>
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={handleCopy}
                    className={`px-3 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-wider transition-all cursor-pointer ${t.buttonSecondary}`}
                  >
                    Copy
                  </button>
                  <button
                    type="button"
                    onClick={handleDownload}
                    className={`px-3 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-wider transition-all cursor-pointer ${t.buttonPrimary}`}
                  >
                    Download
                  </button>
                </div>
              </div>

              <pre className="p-5 text-xs font-mono leading-relaxed overflow-x-auto overflow-y-auto max-h-[600px] whitespace-pre-wrap break-words">
                {output}
              </pre>

              <div className={`px-5 pb-4 text-[10px] font-medium ${t.label}`}>
                Generated client-side — no data leaves your browser
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BundlerGenerator;
