import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { useTheme } from "../../../context/ThemeContext";

const STACKS = ["Node.js", "Python", "Go", "Rust", "PHP", "Ruby"];

const VERSION_PLACEHOLDERS = {
  "Node.js": "20",
  Python: "3.12",
  Go: "1.22",
  Rust: "1.78",
  PHP: "8.3",
  Ruby: "3.3",
};

const getDefaultRunCommand = (stack, environment, containerPort) => {
  const port = String(containerPort);
  const defaults = {
    "Node.js": {
      development: "npm run dev",
      production: "node dist/index.js",
    },
    Python: {
      development: `uvicorn app:app --host 0.0.0.0 --port ${port} --reload`,
      production: `gunicorn --bind 0.0.0.0:${port} app:app`,
    },
    Go: {
      development: "go run ./cmd/server",
      production: "./server",
    },
    Rust: {
      development: "cargo run",
      production: "./app",
    },
    PHP: {
      development: "php-fpm",
      production: "php-fpm",
    },
    Ruby: {
      development: `bundle exec rails server -b 0.0.0.0 -p ${port}`,
      production: `bundle exec rails server -b 0.0.0.0 -p ${port} -e production`,
    },
  };

  return defaults[stack]?.[environment] ?? "npm start";
};

const formatDockerCmd = (runCommand) => {
  const trimmed = (runCommand || "").trim();
  if (!trimmed) return 'CMD ["sh", "-c", "echo No run command specified"]';
  if (trimmed.startsWith("[")) return `CMD ${trimmed}`;
  return `CMD ${trimmed}`;
};

const SERVICE_META = {
  postgresql: { label: "PostgreSQL", composeName: "postgres" },
  mysql: { label: "MySQL", composeName: "mysql" },
  redis: { label: "Redis", composeName: "redis" },
  mongodb: { label: "MongoDB", composeName: "mongodb" },
};

const DEFAULT_SERVICE = {
  enabled: false,
  dbName: "",
  user: "",
  password: "",
  persistVolume: true,
};

const createDefaultForm = () => ({
  stack: "Node.js",
  version: "20",
  runCommand: getDefaultRunCommand("Node.js", "development", 3000),
  containerPort: 3000,
  hostPort: 3000,
  environment: "development",
  customEnvVars: [],
  services: {
    postgresql: {
      ...DEFAULT_SERVICE,
      dbName: "appdb",
      user: "appuser",
      password: "secret",
    },
    mysql: {
      ...DEFAULT_SERVICE,
      dbName: "appdb",
      user: "appuser",
      password: "secret",
    },
    redis: {
      ...DEFAULT_SERVICE,
      dbName: "0",
      user: "default",
      password: "",
    },
    mongodb: {
      ...DEFAULT_SERVICE,
      dbName: "appdb",
      user: "root",
      password: "secret",
    },
  },
});

const generateDockerfile = (form) => {
  const { stack, version, containerPort, environment, runCommand } = form;
  const isProd = environment === "production";
  const cmd = formatDockerCmd(runCommand);
  const header = "# Generated by DevTasks Docker Configuration Generator\n";

  if (stack === "Node.js") {
    if (isProd) {
      return `${header}
# ── Stage 1: Build ──────────────────────────────────────────
FROM node:${version}-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Build application
COPY . .
RUN npm run build

# ── Stage 2: Production runtime ─────────────────────────────
FROM node:${version}-alpine AS production
WORKDIR /app

ENV NODE_ENV=production

# Create non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Copy built assets and production dependencies
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

USER appuser

EXPOSE ${containerPort}

${cmd}
`;
    }

    return `${header}
FROM node:${version}-alpine
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

EXPOSE ${containerPort}

# Development server with hot-reload support
${cmd}
`;
  }

  if (stack === "Python") {
    if (isProd) {
      return `${header}
# ── Stage 1: Build dependencies ─────────────────────────────
FROM python:${version}-slim AS builder
WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip
COPY requirements.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

# ── Stage 2: Production runtime ─────────────────────────────
FROM python:${version}-slim AS production
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Copy installed packages from builder
COPY --from=builder /install /usr/local

# Copy application code
COPY . .

# Create non-root user
RUN useradd -m appuser && chown -R appuser:appuser /app
USER appuser

EXPOSE ${containerPort}

${cmd}
`;
    }

    return `${header}
FROM python:${version}-slim
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

EXPOSE ${containerPort}

# Development server with auto-reload
${cmd}
`;
  }

  if (stack === "Go") {
    if (isProd) {
      return `${header}
# ── Stage 1: Build binary ───────────────────────────────────
FROM golang:${version}-alpine AS builder
WORKDIR /app

RUN apk add --no-cache git ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app/server ./cmd/server

# ── Stage 2: Minimal runtime ────────────────────────────────
FROM alpine:latest AS production
WORKDIR /app

RUN apk add --no-cache ca-certificates

# Copy compiled binary
COPY --from=builder /app/server .

# Create non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

EXPOSE ${containerPort}

${cmd}
`;
    }

    return `${header}
FROM golang:${version}-alpine
WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE ${containerPort}

# Development with live reload (requires air or similar in project)
${cmd}
`;
  }

  if (stack === "Rust") {
    if (isProd) {
      return `${header}
# ── Stage 1: Build release binary ───────────────────────────
FROM rust:${version}-alpine AS builder
WORKDIR /app

RUN apk add --no-cache musl-dev

COPY Cargo.toml Cargo.lock ./
COPY src ./src

RUN cargo build --release

# ── Stage 2: Minimal runtime ────────────────────────────────
FROM alpine:latest AS production
WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/target/release/app .

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

EXPOSE ${containerPort}

${cmd}
`;
    }

    return `${header}
FROM rust:${version}-alpine
WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY src ./src

EXPOSE ${containerPort}

# Development build and run
${cmd}
`;
  }

  if (stack === "PHP") {
    if (isProd) {
      return `${header}
# ── Stage 1: Install dependencies ───────────────────────────
FROM composer:latest AS builder
WORKDIR /app

COPY composer.json composer.lock ./
RUN composer install --no-dev --optimize-autoloader --no-interaction

# ── Stage 2: Production runtime ─────────────────────────────
FROM php:${version}-fpm-alpine AS production
WORKDIR /app

# Copy vendor and application code
COPY --from=builder /app/vendor ./vendor
COPY . .

# Create non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

EXPOSE ${containerPort}

${cmd}
`;
    }

    return `${header}
FROM php:${version}-fpm-alpine
WORKDIR /app

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock ./
RUN composer install

COPY . .

EXPOSE ${containerPort}

${cmd}
`;
  }

  if (stack === "Ruby") {
    if (isProd) {
      return `${header}
# ── Stage 1: Install gems ───────────────────────────────────
FROM ruby:${version}-slim AS builder
WORKDIR /app

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN bundle config set --local deployment 'true' && \\
    bundle config set --local without 'development test' && \\
    bundle install

# ── Stage 2: Production runtime ───────────────────────────────
FROM ruby:${version}-slim AS production
WORKDIR /app

ENV RAILS_ENV=production
ENV BUNDLE_WITHOUT="development:test"

COPY --from=builder /usr/local/bundle /usr/local/bundle
COPY . .

RUN useradd -m appuser && chown -R appuser:appuser /app
USER appuser

EXPOSE ${containerPort}

${cmd}
`;
    }

    return `${header}
FROM ruby:${version}-slim
WORKDIR /app

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE ${containerPort}

# Development server with hot-reload support
${cmd}
`;
  }

  return `${header}# Unsupported stack\n`;
};

const getEnabledServices = (services) =>
  Object.entries(services).filter(([, cfg]) => cfg.enabled);

const generateDockerCompose = (form) => {
  const {
    stack,
    containerPort,
    hostPort,
    environment,
    services,
    customEnvVars,
  } = form;
  const isDev = environment === "development";
  const enabled = getEnabledServices(services);

  const lines = [
    "# Generated by DevTasks Docker Configuration Generator",
    'version: "3.9"',
    "",
    "services:",
    "  # Main application service",
    "  app:",
    "    build: .",
    "    ports:",
    `      - "${hostPort}:${containerPort}"`,
    "    environment:",
    `      NODE_ENV: ${isDev ? "development" : "production"}`,
  ];

  (customEnvVars || []).forEach(({ key, value }) => {
    const trimmedKey = (key || "").trim();
    if (trimmedKey) {
      lines.push(`      ${trimmedKey}: ${value ?? ""}`);
    }
  });

  if (enabled.length > 0) {
    enabled.forEach(([key, cfg]) => {
      const { composeName } = SERVICE_META[key];
      if (key === "postgresql") {
        lines.push(
          `      DATABASE_URL: postgresql://${cfg.user}:${cfg.password}@${composeName}:5432/${cfg.dbName}`,
        );
      } else if (key === "mysql") {
        lines.push(
          `      DATABASE_URL: mysql://${cfg.user}:${cfg.password}@${composeName}:3306/${cfg.dbName}`,
        );
      } else if (key === "redis") {
        const auth = cfg.password ? `:${cfg.password}@` : "";
        lines.push(
          `      REDIS_URL: redis://${auth}${composeName}:6379/${cfg.dbName}`,
        );
      } else if (key === "mongodb") {
        lines.push(
          `      MONGODB_URI: mongodb://${cfg.user}:${cfg.password}@${composeName}:27017/${cfg.dbName}`,
        );
      }
    });

    lines.push("    depends_on:");
    enabled.forEach(([key]) => {
      lines.push(`      - ${SERVICE_META[key].composeName}`);
    });
  }

  if (isDev) {
    lines.push("    volumes:");
    lines.push("      - .:/app");
    if (stack === "Node.js") {
      lines.push("      - /app/node_modules");
    }
    if (stack === "Ruby") {
      lines.push("      - /usr/local/bundle");
    }
  }

  lines.push("    restart: unless-stopped");
  lines.push("");

  enabled.forEach(([key, cfg]) => {
    const { composeName } = SERVICE_META[key];

    if (key === "postgresql") {
      lines.push(`  # PostgreSQL database service`);
      lines.push(`  ${composeName}:`);
      lines.push(`    image: postgres:16-alpine`);
      lines.push(`    environment:`);
      lines.push(`      POSTGRES_DB: ${cfg.dbName}`);
      lines.push(`      POSTGRES_USER: ${cfg.user}`);
      lines.push(`      POSTGRES_PASSWORD: ${cfg.password}`);
      lines.push(`    ports:`);
      lines.push(`      - "5432:5432"`);
      if (cfg.persistVolume) {
        lines.push(`    volumes:`);
        lines.push(`      - postgres_data:/var/lib/postgresql/data`);
      }
      lines.push(`    restart: unless-stopped`);
      lines.push("");
    } else if (key === "mysql") {
      lines.push(`  # MySQL database service`);
      lines.push(`  ${composeName}:`);
      lines.push(`    image: mysql:8`);
      lines.push(`    environment:`);
      lines.push(`      MYSQL_DATABASE: ${cfg.dbName}`);
      lines.push(`      MYSQL_USER: ${cfg.user}`);
      lines.push(`      MYSQL_PASSWORD: ${cfg.password}`);
      lines.push(`      MYSQL_ROOT_PASSWORD: ${cfg.password}`);
      lines.push(`    ports:`);
      lines.push(`      - "3306:3306"`);
      if (cfg.persistVolume) {
        lines.push(`    volumes:`);
        lines.push(`      - mysql_data:/var/lib/mysql`);
      }
      lines.push(`    restart: unless-stopped`);
      lines.push("");
    } else if (key === "redis") {
      lines.push(`  # Redis cache service`);
      lines.push(`  ${composeName}:`);
      lines.push(`    image: redis:7-alpine`);
      if (cfg.password) {
        lines.push(`    command: redis-server --requirepass ${cfg.password}`);
      }
      lines.push(`    ports:`);
      lines.push(`      - "6379:6379"`);
      if (cfg.persistVolume) {
        lines.push(`    volumes:`);
        lines.push(`      - redis_data:/data`);
      }
      lines.push(`    restart: unless-stopped`);
      lines.push("");
    } else if (key === "mongodb") {
      lines.push(`  # MongoDB database service`);
      lines.push(`  ${composeName}:`);
      lines.push(`    image: mongo:7`);
      lines.push(`    environment:`);
      lines.push(`      MONGO_INITDB_DATABASE: ${cfg.dbName}`);
      lines.push(`      MONGO_INITDB_ROOT_USERNAME: ${cfg.user}`);
      lines.push(`      MONGO_INITDB_ROOT_PASSWORD: ${cfg.password}`);
      lines.push(`    ports:`);
      lines.push(`      - "27017:27017"`);
      if (cfg.persistVolume) {
        lines.push(`    volumes:`);
        lines.push(`      - mongo_data:/data/db`);
      }
      lines.push(`    restart: unless-stopped`);
      lines.push("");
    }
  });

  const volumeNames = enabled
    .filter(([, cfg]) => cfg.persistVolume)
    .map(([key]) => {
      if (key === "postgresql") return "postgres_data";
      if (key === "mysql") return "mysql_data";
      if (key === "redis") return "redis_data";
      if (key === "mongodb") return "mongo_data";
      return null;
    })
    .filter(Boolean);

  if (volumeNames.length > 0) {
    lines.push("volumes:");
    volumeNames.forEach((name) => {
      lines.push(`  ${name}:`);
    });
  }

  return lines.join("\n");
};

const DockerGenerator = () => {
  const { dark } = useTheme();
  const [form, setForm] = useState(createDefaultForm);
  const [activeOutputTab, setActiveOutputTab] = useState("dockerfile");

  const theme = {
    light: {
      wrapper: "bg-[#F8F9FA] text-zinc-900",
      card: "bg-white border-zinc-250/90 shadow-sm",
      headerBorder: "border-zinc-200",
      input:
        "bg-white border-zinc-250 text-zinc-900 focus:border-zinc-900 placeholder-zinc-400 focus:bg-white",
      buttonPrimary:
        "bg-zinc-900 text-white hover:bg-zinc-800 active:scale-[0.98]",
      buttonSecondary:
        "bg-white border-zinc-250 text-zinc-700 hover:bg-zinc-50 active:scale-[0.98]",
      label: "text-zinc-500",
      subCard: "bg-neutral-50 border-neutral-200",
      outputPre: "bg-[#F9FAFB] border-zinc-200 text-emerald-700",
      tabActive: "bg-black text-white",
      tabInactive: "bg-neutral-200 text-neutral-600",
      toggleActive: "bg-black text-white",
      toggleInactive: "bg-neutral-200 text-neutral-600",
    },
    dark: {
      wrapper: "bg-[#090A0F] text-zinc-100",
      card: "bg-zinc-900/50 border-zinc-800/80 shadow-[0_8px_30px_rgb(0,0,0,0.4)]",
      headerBorder: "border-zinc-800/85",
      input:
        "bg-zinc-950/60 border-zinc-800 text-white focus:border-zinc-500 placeholder-zinc-600 focus:bg-zinc-950",
      buttonPrimary:
        "bg-white text-zinc-950 hover:bg-zinc-100 active:scale-[0.98]",
      buttonSecondary:
        "bg-zinc-900 border-zinc-800/80 text-zinc-300 hover:bg-zinc-850 active:scale-[0.98]",
      label: "text-zinc-400",
      subCard: "bg-zinc-950/60 border-zinc-800",
      outputPre: "bg-zinc-950/80 border-zinc-800/80 text-emerald-400",
      tabActive: "bg-white text-black",
      tabInactive: "bg-zinc-800 text-zinc-400",
      toggleActive: "bg-white text-black",
      toggleInactive: "bg-zinc-800 text-zinc-400",
    },
  };
  const t = dark ? theme.dark : theme.light;

  const dockerfile = useMemo(() => generateDockerfile(form), [form]);
  const composeYaml = useMemo(() => generateDockerCompose(form), [form]);
  const activeOutput =
    activeOutputTab === "dockerfile" ? dockerfile : composeYaml;

  const updateField = (field, value) => {
    setForm((prev) => ({ ...prev, [field]: value }));
  };

  const handleStackChange = (stack) => {
    setForm((prev) => ({
      ...prev,
      stack,
      version: VERSION_PLACEHOLDERS[stack] || prev.version,
      runCommand: getDefaultRunCommand(
        stack,
        prev.environment,
        prev.containerPort,
      ),
    }));
  };

  const handleEnvironmentChange = (environment) => {
    setForm((prev) => ({
      ...prev,
      environment,
      runCommand: getDefaultRunCommand(
        prev.stack,
        environment,
        prev.containerPort,
      ),
    }));
  };

  const handlePortChange = (field, value) => {
    setForm((prev) => {
      const next = { ...prev, [field]: value };
      const defaultCmd = getDefaultRunCommand(
        prev.stack,
        prev.environment,
        next.containerPort,
      );
      const prevDefault = getDefaultRunCommand(
        prev.stack,
        prev.environment,
        prev.containerPort,
      );
      if (prev.runCommand === prevDefault) {
        next.runCommand = defaultCmd;
      }
      return next;
    });
  };

  const addEnvVar = () => {
    setForm((prev) => ({
      ...prev,
      customEnvVars: [
        ...prev.customEnvVars,
        { id: crypto.randomUUID(), key: "", value: "" },
      ],
    }));
  };

  const removeEnvVar = (id) => {
    setForm((prev) => ({
      ...prev,
      customEnvVars: prev.customEnvVars.filter((item) => item.id !== id),
    }));
  };

  const updateEnvVar = (id, field, value) => {
    setForm((prev) => ({
      ...prev,
      customEnvVars: prev.customEnvVars.map((item) =>
        item.id === id ? { ...item, [field]: value } : item,
      ),
    }));
  };

  const toggleService = (key) => {
    setForm((prev) => ({
      ...prev,
      services: {
        ...prev.services,
        [key]: {
          ...prev.services[key],
          enabled: !prev.services[key].enabled,
        },
      },
    }));
  };

  const updateService = (key, field, value) => {
    setForm((prev) => ({
      ...prev,
      services: {
        ...prev.services,
        [key]: {
          ...prev.services[key],
          [field]: value,
        },
      },
    }));
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(activeOutput);
      toast.success("Copied to clipboard", {
        style: { background: "#000000", color: "#ffffff" },
      });
    } catch {
      toast.error("Failed to copy", {
        style: { background: "#000000", color: "#ffffff" },
      });
    }
  };

  const handleDownload = () => {
    const filename =
      activeOutputTab === "dockerfile" ? "Dockerfile" : "docker-compose.yml";
    const blob = new Blob([activeOutput], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success(`Downloaded ${filename}`, {
      style: { background: "#000000", color: "#ffffff" },
    });
  };

  const inputClass = `w-full px-4 py-2.5 rounded-xl border text-sm outline-none transition-all duration-300 ${t.input}`;
  const labelClass = `text-xs font-black uppercase tracking-widest ${t.label}`;

  return (
    <div
      className={`min-h-[calc(100vh-76px)] px-4 py-8 flex items-start justify-center transition-colors duration-300 ${t.wrapper}`}
    >
      <title>Docker Configuration Generator — DevTasks</title>
      <meta
        name="description"
        content="Generate production-ready Dockerfile and docker-compose.yml configurations client-side."
      />

      <div
        className={`w-full max-w-6xl rounded-3xl border overflow-hidden transition-all duration-300 ${t.card}`}
      >
        <div
          className={`flex items-center gap-4 p-5 border-b ${t.headerBorder}`}
        >
          <Link
            to="/devutilities"
            className={`w-10 h-10 border rounded-xl flex items-center justify-center font-bold text-lg transition-all duration-200 ${t.buttonSecondary}`}
            title="Back to Utilities"
          >
            ←
          </Link>
          <div>
            <h1 className="text-xl font-black uppercase tracking-tight">
              Docker Configuration Generator
            </h1>
            <p className={`text-xs font-semibold mt-0.5 ${t.label}`}>
              Generate production-ready Dockerfile and docker-compose.yml
              configurations client-side.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 p-6">
          {/* Form Panel */}
          <div className="flex flex-col gap-5">
            <h2 className="text-xs font-black uppercase tracking-[0.2em]">
              Configuration
            </h2>

            {/* Base Stack */}
            <div className="flex flex-col gap-3">
              <span className={labelClass}>Base Stack</span>
              <select
                value={form.stack}
                onChange={(e) => handleStackChange(e.target.value)}
                className={inputClass}
              >
                {STACKS.map((s) => (
                  <option key={s} value={s}>
                    {s}
                  </option>
                ))}
              </select>
              <div className="flex flex-col gap-2">
                <label className={labelClass}>Runtime Version</label>
                <input
                  type="text"
                  value={form.version}
                  onChange={(e) => updateField("version", e.target.value)}
                  placeholder={VERSION_PLACEHOLDERS[form.stack]}
                  className={inputClass}
                />
              </div>
            </div>

            {/* Run Command */}
            <div className="flex flex-col gap-3">
              <span className={labelClass}>Run Command</span>
              <input
                type="text"
                value={form.runCommand}
                onChange={(e) => updateField("runCommand", e.target.value)}
                placeholder={getDefaultRunCommand(
                  form.stack,
                  form.environment,
                  form.containerPort,
                )}
                className={`${inputClass} font-mono`}
              />
              <p className={`text-[10px] font-medium ${t.label}`}>
                Used as the Dockerfile CMD instruction (e.g. npm start, bundle
                exec rails server).
              </p>
            </div>

            {/* Network & Ports */}
            <div className="flex flex-col gap-3">
              <span className={labelClass}>Network &amp; Ports</span>
              <div className="grid grid-cols-2 gap-3">
                <div className="flex flex-col gap-2">
                  <label className={labelClass}>Container Port</label>
                  <input
                    type="number"
                    min={1}
                    max={65535}
                    value={form.containerPort}
                    onChange={(e) =>
                      handlePortChange(
                        "containerPort",
                        Number(e.target.value) || 1,
                      )
                    }
                    className={inputClass}
                  />
                </div>
                <div className="flex flex-col gap-2">
                  <label className={labelClass}>Host Port</label>
                  <input
                    type="number"
                    min={1}
                    max={65535}
                    value={form.hostPort}
                    onChange={(e) =>
                      updateField("hostPort", Number(e.target.value) || 1)
                    }
                    className={inputClass}
                  />
                </div>
              </div>
            </div>

            {/* Environment Toggle */}
            <div className="flex flex-col gap-3">
              <span className={labelClass}>Environment</span>
              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={() => handleEnvironmentChange("production")}
                  className={`flex-1 px-4 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wide transition-all cursor-pointer ${
                    form.environment === "production"
                      ? t.toggleActive
                      : t.toggleInactive
                  }`}
                >
                  Production
                </button>
                <button
                  type="button"
                  onClick={() => handleEnvironmentChange("development")}
                  className={`flex-1 px-4 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wide transition-all cursor-pointer ${
                    form.environment === "development"
                      ? t.toggleActive
                      : t.toggleInactive
                  }`}
                >
                  Development
                </button>
              </div>
              <p className={`text-[10px] font-medium ${t.label}`}>
                {form.environment === "production"
                  ? "Multi-stage optimized Dockerfile templates."
                  : "Includes local volume mounts for hot-reloading in compose."}
              </p>
            </div>

            {/* Custom Environment Variables */}
            <div className="flex flex-col gap-3">
              <div className="flex items-center justify-between">
                <span className={labelClass}>Environment Variables</span>
                <button
                  type="button"
                  onClick={addEnvVar}
                  className={`px-3 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-wider transition-all cursor-pointer ${t.buttonSecondary}`}
                >
                  + Add
                </button>
              </div>
              {form.customEnvVars.length === 0 ? (
                <p className={`text-[10px] font-medium ${t.label}`}>
                  No custom variables. Click Add to inject env vars into
                  docker-compose.yml.
                </p>
              ) : (
                <div className="flex flex-col gap-2">
                  {form.customEnvVars.map((envVar) => (
                    <div
                      key={envVar.id}
                      className={`rounded-xl border p-3 flex flex-col sm:flex-row gap-2 ${t.subCard}`}
                    >
                      <input
                        type="text"
                        value={envVar.key}
                        onChange={(e) =>
                          updateEnvVar(envVar.id, "key", e.target.value)
                        }
                        placeholder="KEY"
                        className={`${inputClass} font-mono uppercase flex-1`}
                      />
                      <input
                        type="text"
                        value={envVar.value}
                        onChange={(e) =>
                          updateEnvVar(envVar.id, "value", e.target.value)
                        }
                        placeholder="value"
                        className={`${inputClass} font-mono flex-1`}
                      />
                      <button
                        type="button"
                        onClick={() => removeEnvVar(envVar.id)}
                        className={`px-3 py-2 rounded-lg text-[10px] font-black uppercase tracking-wider transition-all cursor-pointer shrink-0 ${t.buttonSecondary}`}
                        aria-label="Remove environment variable"
                      >
                        Remove
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Services */}
            <div className="flex flex-col gap-3">
              <span className={labelClass}>Services</span>
              {Object.entries(SERVICE_META).map(([key, meta]) => {
                const svc = form.services[key];
                return (
                  <div
                    key={key}
                    className={`rounded-2xl border p-4 transition-colors ${t.subCard}`}
                  >
                    <label className="flex items-center gap-3 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={svc.enabled}
                        onChange={() => toggleService(key)}
                        className="w-4 h-4 rounded accent-zinc-900"
                      />
                      <span className="text-sm font-bold uppercase tracking-wide">
                        {meta.label}
                      </span>
                    </label>

                    {svc.enabled && (
                      <div className="mt-4 flex flex-col gap-3 pl-7">
                        <div className="flex flex-col gap-2">
                          <label className={labelClass}>Database Name</label>
                          <input
                            type="text"
                            value={svc.dbName}
                            onChange={(e) =>
                              updateService(key, "dbName", e.target.value)
                            }
                            className={inputClass}
                          />
                        </div>
                        <div className="flex flex-col gap-2">
                          <label className={labelClass}>User</label>
                          <input
                            type="text"
                            value={svc.user}
                            onChange={(e) =>
                              updateService(key, "user", e.target.value)
                            }
                            className={inputClass}
                          />
                        </div>
                        <div className="flex flex-col gap-2">
                          <label className={labelClass}>Password</label>
                          <input
                            type="text"
                            value={svc.password}
                            onChange={(e) =>
                              updateService(key, "password", e.target.value)
                            }
                            className={inputClass}
                          />
                        </div>
                        <label className="flex items-center gap-3 cursor-pointer">
                          <input
                            type="checkbox"
                            checked={svc.persistVolume}
                            onChange={(e) =>
                              updateService(
                                key,
                                "persistVolume",
                                e.target.checked,
                              )
                            }
                            className="w-4 h-4 rounded accent-zinc-900"
                          />
                          <span className={`text-xs font-semibold ${t.label}`}>
                            Volume Persistence
                          </span>
                        </label>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Output Panel */}
          <div className="flex flex-col gap-4">
            <h2 className="text-xs font-black uppercase tracking-[0.2em]">
              Output
            </h2>

            <div
              className={`rounded-2xl border overflow-hidden flex flex-col ${t.outputPre}`}
            >
              <div
                className={`flex items-center justify-between px-4 py-3 border-b ${t.headerBorder}`}
              >
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={() => setActiveOutputTab("dockerfile")}
                    className={`px-4 py-1.5 rounded-xl text-xs font-black uppercase tracking-widest transition-all cursor-pointer ${
                      activeOutputTab === "dockerfile"
                        ? t.tabActive
                        : t.tabInactive
                    }`}
                  >
                    Dockerfile
                  </button>
                  <button
                    type="button"
                    onClick={() => setActiveOutputTab("compose")}
                    className={`px-4 py-1.5 rounded-xl text-xs font-black uppercase tracking-widest transition-all cursor-pointer ${
                      activeOutputTab === "compose"
                        ? t.tabActive
                        : t.tabInactive
                    }`}
                  >
                    docker-compose.yml
                  </button>
                </div>
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={handleCopy}
                    className={`px-3 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-wider transition-all cursor-pointer ${t.buttonSecondary}`}
                  >
                    Copy
                  </button>
                  <button
                    type="button"
                    onClick={handleDownload}
                    className={`px-3 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-wider transition-all cursor-pointer ${t.buttonPrimary}`}
                  >
                    Download
                  </button>
                </div>
              </div>

              <pre className="p-5 text-xs font-mono leading-relaxed overflow-x-auto overflow-y-auto max-h-[600px] whitespace-pre-wrap break-words">
                {activeOutput}
              </pre>

              <div className={`px-5 pb-4 text-[10px] font-medium ${t.label}`}>
                Generated client-side — no data leaves your browser
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DockerGenerator;
